
spring.application.name=GreenSteel-Backend

spring.datasource.url=jdbc:mysql://localhost:3306/greensteel
spring.datasource.username=root
spring.datasource.password=REDACTED
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=8B5A9D4F1E6C7A2B3D8E9F0A1B2C3D4E5F6A7B8C9D0E1F2A3B4C5D6E7F8A9B0C
jwt.expiration=86400000